### ISSUE TITLE
code dependence 

### ISSUE THREAD

**Issue by lauranceair** [DeepTrial/Retina-VesselNet#24]
hi 
i use your environment but have some problems

Traceback (most recent call last):
  File "main_train.py", line 54, in <module>
    main_train()
  File "main_train.py", line 35, in main_train
    dataloader.prepare_dataset()
  File "/home/air/Desktop/BioHiLab/Retina-VesselNet/experiments/data_loaders/standard_loader.py", line 72, in prepare_dataset
    imgs_train, groundTruth=self._access_dataset(self.train_img_path,self.train_groundtruth_path,self.train_type)
  File "/home/air/Desktop/BioHiLab/Retina-VesselNet/experiments/data_loaders/standard_loader.py", line 63, in _access_dataset
    assert (np.max(groundTruth) == 255)
  File "/home/air/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2320, in amax
    out=out, **kwargs)
  File "/home/air/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by xuchunyuan** [comment]
download the 'VesselNet' and put it under the 'experiments'
the route like this:
Retina-VesselNet-master\experiments\VesselNet

**Comment by lauranceair** [comment]
> download the 'VesselNet' and put it under the 'experiments'
> the route like this:
> Retina-VesselNet-master\experiments\VesselNet

十分感谢，已经调通了，这个代码非常好用
