### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './experiments/VesselNet/dataset/train/groundtruth/./emanual1.tif'

### ISSUE THREAD

**Issue by llmir** [DeepTrial/Retina-VesselNet#25]
This message comes up when running main_training.py

I don't understand where this error is coming from as I cannot find where we are actually looking for a file 'emanual1.tif'.

Did someone run in the same issue?

**Comment by DeepTrial** [comment]
i think this error is about the problem of image path. how do u organize the train image data?

**Comment by llmir** [comment]
thx, but i just copy your files in VesselNet and paste them at the same place. And i have saw the same issue closed sevaral months ago without a solution to this issue.

**Comment by llmir** [comment]
Traceback (most recent call last):
  File "main_train.py", line 54, in <module>
    main_train()
  File "main_train.py", line 35, in main_train
    dataloader.prepare_dataset()
  File "/home/mir/Retina-VesselNet/experiments/data_loaders/standard_loader.py", line 72, in prepare_dataset
    imgs_train, groundTruth=self._access_dataset(self.train_img_path,self.train_groundtruth_path,self.train_type)
  File "/home/mir/Retina-VesselNet/experiments/data_loaders/standard_loader.py", line 60, in _access_dataset
    gtImg=plt.imread(gtPath,0)
  File "/home/mir/anaconda3/envs/tf2/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2152, in imread
    return matplotlib.image.imread(fname, format)
  File "/home/mir/anaconda3/envs/tf2/lib/python3.6/site-packages/matplotlib/image.py", line 1351, in imread
    with Image.open(fname) as image:
  File "/home/mir/anaconda3/envs/tf2/lib/python3.6/site-packages/PIL/Image.py", line 2652, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './experiments/VesselNet/dataset/train/groundtruth/./emanual1.tif'


this is the whole Traceback.

**Comment by DeepTrial** [comment]
i‘ve noticed that you try to run the code in ubuntu, i setup up the model in win10, maybe the problem is the different type of file path like '/' and '\'.
