### ISSUE TITLE
Error while running main_test.py

### ISSUE THREAD

**Issue by venkat8900** [DeepTrial/Retina-VesselNet#38]
I'm getting the following error when i'm running main_test.py

tempfile.tif: Cannot read TIFF header.
Traceback (most recent call last):
  File "main_test.py", line 41, in <module>
    main_test()
  File "main_test.py", line 29, in main_test
    infer.predict()
  File "C:\Users\Venkat M\Downloads\Retina-VesselNet-master\Retina-VesselNet-master\perception\infers\segmention_infer.py", line 33, in predict
    orgImg=[orgImg_temp[:,:,1]*0.75]+[orgImg_temp[:,:,0]*0.25]
IndexError: too many indices for array

**Comment by DeepTrial** [comment]
I have update the code. You can find the method  on the jupyter notebook.  if you still have the problem, open the issue again
